### ISSUE TITLE
App wants too many GitHub permissions

### ISSUE THREAD

**Issue by fw42** [arthurnn/policial.io#12]
![screen shot 2015-05-15 at 11 34 11 am](https://cloud.githubusercontent.com/assets/2072686/7656108/535735e8-faf6-11e4-80fd-3892e4001f03.png)

**Comment by arthurnn** [comment]
Yeah thats too much. Ideally for login we should only require read access to User. And on the repositories page, we can have a button like "List private repos" (that will ask more permissions), and on the "Add webhook" link we could ask more permissions too.
